# -*- coding: utf-8 -*-
"""HSegFormer_arcitecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpSv0wVNliJ9558P0nOxHqbLK7mNx4mS
"""

#==================================================================================================
# HSegFormer+ (Rev) — Brain Tumor Segmentation
# Decoder with Attention Gates + ASPP, Deep Supervision
# Fixed Input=512, Fixed Batch Size=8 (assert enforced)
# ==================================================================================================
import os
import time
import math
import random
import argparse
from pathlib import Path
from typing import List, Tuple

import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from torchvision import models, transforms
from transformers import SegformerModel, AutoConfig

# -----------------------------
# Global fixed configs
# -----------------------------
FIXED_IMG_SIZE = 512
FIXED_BATCH_SIZE = 8

# -----------------------------
# Building blocks
# -----------------------------
class NABlock(nn.Module):
    """DW 3x3 + PW 1x1 + GN + GELU + SE."""
    def __init__(self, dim):
        super().__init__()
        self.dw = nn.Conv2d(dim, dim, 3, padding=1, groups=dim, bias=False)
        self.pw = nn.Conv2d(dim, dim, 1, bias=False)
        self.gn = nn.GroupNorm(8, dim)
        self.act = nn.GELU()
        self.se = nn.Sequential(
               nn.AdaptiveAvgPool2d(1),
               nn.Conv2d(dim, dim // reduction, 1),
               nn.GELU(),
               nn.Conv2d(dim // reduction, dim, 1),
               nn.Sigmoid()
               )
    def forward(self, x):
        y = self.dw(x)
        y = self.pw(y)
        y = self.gn(y)
        y = self.act(y)
        y = y * self.se(y)
        return y


class AttentionGate(nn.Module):

    def __init__(self, in_ch_skip, in_ch_g, inter_ch):
        super().__init__()

        self.theta = nn.Conv2d(
            in_ch_skip,
            inter_ch,
            kernel_size=1,
            bias=True
        )

        self.phi = nn.Conv2d(
            in_ch_g,
            inter_ch,
            kernel_size=1,
            bias=True
        )

        self.psi = nn.Conv2d(
            inter_ch,
            1,
            kernel_size=1,
            bias=True
        )

        self.relu = nn.ReLU(inplace=True)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x_skip, g):

        q = self.theta(x_skip) + self.phi(g)

        q = self.relu(q)

        alpha = self.sigmoid(self.psi(q))

        return x_skip * alpha

class ASPP(nn.Module):
    def __init__(self, in_ch, out_ch, rates=(1, 6, 12, 18)):
        super().__init__()

        # Multi-scale atrous branches
        self.branches = nn.ModuleList([
            nn.Conv2d(in_ch, out_ch, kernel_size=1, bias=False)
        ])

        for r in rates[1:]:
            self.branches.append(
                nn.Conv2d(
                    in_ch,
                    out_ch,
                    kernel_size=3,
                    padding=r,
                    dilation=r,
                    bias=False
                )
            )

        # Image-level pooling branch
        self.image_pool = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(in_ch, out_ch, kernel_size=1, bias=False)
        )

        # Feature compression (1×1 Conv)
        self.project = nn.Conv2d(
            out_ch * (len(self.branches) + 1),
            out_ch,
            kernel_size=1,
            bias=False
        )

    def forward(self, x):

        feats = [branch(x) for branch in self.branches]

        img = self.image_pool(x)
        img = F.interpolate(
            img,
            size=x.shape[-2:],
            mode='bilinear',
            align_corners=False
        )

        feats.append(img)

        x = torch.cat(feats, dim=1)

        x = self.project(x)

        return x

# -------------------------------------------------------------
# Hybrid Encoder (SegFormer-B5 + ResNet-50)
# -------------------------------------------------------------
class HybridEncoder(nn.Module):
    """
    Hybrid CNN-Transformer encoder.

    Output:
        F4, F8, F16, F32
    """

    def __init__(
        self,
        backbone_name="nvidia/mit-b5",
        fuse_dim=128,
        pretrained=True,
    ):
        super().__init__()

        # -------------------------------------------------
        # Transformer Branch (SegFormer-B5)
        # -------------------------------------------------
        if pretrained:
            self.segformer = SegformerModel.from_pretrained(
                backbone_name,
                output_hidden_states=True
            )
        else:
            cfg = AutoConfig.from_pretrained(backbone_name)
            cfg.output_hidden_states = True
            self.segformer = SegformerModel(cfg)

        # -------------------------------------------------
        # CNN Branch (ResNet-50)
        # -------------------------------------------------
        resnet = models.resnet50(
            weights=models.ResNet50_Weights.IMAGENET1K_V2
            if pretrained else None
        )

        self.conv1 = nn.Sequential(
            resnet.conv1,
            resnet.bn1,
            resnet.relu
        )

        self.pool = resnet.maxpool

        self.layer1 = resnet.layer1
        self.layer2 = resnet.layer2
        self.layer3 = resnet.layer3
        self.layer4 = resnet.layer4

        # -------------------------------------------------
        # Feature Projection
        # -------------------------------------------------

        self.proj_trans = nn.ModuleList([
            nn.Conv2d(64, fuse_dim, kernel_size=1),
            nn.Conv2d(128, fuse_dim, kernel_size=1),
            nn.Conv2d(320, fuse_dim, kernel_size=1),
            nn.Conv2d(512, fuse_dim, kernel_size=1),
        ])

        self.proj_cnn = nn.ModuleList([
            nn.Conv2d(256, fuse_dim, kernel_size=1),
            nn.Conv2d(512, fuse_dim, kernel_size=1),
            nn.Conv2d(1024, fuse_dim, kernel_size=1),
            nn.Conv2d(2048, fuse_dim, kernel_size=1),
        ])

        fusion_channels = fuse_dim * 2

        # -------------------------------------------------
        # Stage-wise Feature Fusion
        # -------------------------------------------------

        self.na_blocks = nn.ModuleList([
            NABlock(fusion_channels)
            for _ in range(4)
        ])

        self.fuse_conv = nn.ModuleList([
            nn.Conv2d(
                fusion_channels,
                fuse_dim,
                kernel_size=1
            )
            for _ in range(4)
        ])

        self.strides = [4, 8, 16, 32]

        self.transformer_dims = [64, 128, 320, 512]

    @staticmethod
    def reshape_tokens(tokens, B, H, W, C):
        return tokens.transpose(1, 2).reshape(B, C, H, W)

    def transformer_features(self, x):

        B, _, H, W = x.shape

        outputs = self.segformer(pixel_values=x)

        hidden_states = list(outputs.hidden_states)

        T_features = []

        for i, stride in enumerate(self.strides):

            Hi = H // stride
            Wi = W // stride

            T_features.append(
                self.reshape_tokens(
                    hidden_states[i],
                    B,
                    Hi,
                    Wi,
                    self.transformer_dims[i]
                )
            )

        return T_features

    def forward(self, x):

        # -------------------------------------------------
        # Transformer Branch
        # -------------------------------------------------

        T1, T2, T3, T4 = self.transformer_features(x)

        # -------------------------------------------------
        # CNN Branch
        # -------------------------------------------------

        x = self.conv1(x)
        x = self.pool(x)

        R1 = self.layer1(x)
        R2 = self.layer2(R1)
        R3 = self.layer3(R2)
        R4 = self.layer4(R3)

        transformer_features = [T1, T2, T3, T4]
        cnn_features = [R1, R2, R3, R4]

        fused_features = []

        # -------------------------------------------------
        # Projection
        # → Concatenation
        # → NABlock
        # → 1×1 Compression
        # -------------------------------------------------

        for i in range(4):

            P_trans = self.proj_trans[i](transformer_features[i])

            P_cnn = self.proj_cnn[i](cnn_features[i])

            F = torch.cat([P_trans, P_cnn], dim=1)

            F = self.na_blocks[i](F)

            F = self.fuse_conv[i](F)

            fused_features.append(F)

        F4, F8, F16, F32 = fused_features

        return [F4, F8, F16, F32]

# -------------------------------------------------------------
# Decoder (Attention + ASPP + Deep Supervision)
# -------------------------------------------------------------
class UNetFPNDecoder_DS_Attn(nn.Module):

    def __init__(self,
                 fuse_dim=128,
                 out_classes=1,
                 use_deep_supervision=True):

        super().__init__()

        C = fuse_dim

        self.use_deep_supervision = use_deep_supervision

        # -------------------------------------------------
        # Attention Gates
        # -------------------------------------------------

        self.gate32_16 = AttentionGate(C, C, C // 2)
        self.gate16_8  = AttentionGate(C, C, C // 2)
        self.gate8_4   = AttentionGate(C, C, C // 2)

        # -------------------------------------------------
        # Decoder Blocks
        # (Concat -> NABlock -> 1x1 Conv)
        # -------------------------------------------------

        self.na32_16 = NABlock(2 * C)
        self.na16_8  = NABlock(2 * C)
        self.na8_4   = NABlock(2 * C)

        self.reduce32_16 = nn.Conv2d(2 * C, C, kernel_size=1)
        self.reduce16_8  = nn.Conv2d(2 * C, C, kernel_size=1)
        self.reduce8_4   = nn.Conv2d(2 * C, C, kernel_size=1)

        # -------------------------------------------------
        # ASPP
        # -------------------------------------------------

        self.aspp = ASPP(C, C)

        # -------------------------------------------------
        # Prediction Head
        # -------------------------------------------------

        self.head = nn.Conv2d(
            C,
            out_classes,
            kernel_size=1
        )

        # -------------------------------------------------
        # Deep Supervision
        # -------------------------------------------------

        if self.use_deep_supervision:

            self.ds16 = nn.Conv2d(
                C,
                out_classes,
                kernel_size=1
            )

            self.ds8 = nn.Conv2d(
                C,
                out_classes,
                kernel_size=1
            )

    def forward(self, feats):

        F4, F8, F16, F32 = feats

        # =================================================
        # Stage 32 -> 16
        # =================================================

        x = F.interpolate(
            F32,
            size=F16.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        G16 = self.gate32_16(F16, x)

        x = torch.cat([x, G16], dim=1)

        x = self.na32_16(x)

        x = self.reduce32_16(x)

        DS16 = x

        # =================================================
        # Stage 16 -> 8
        # =================================================

        x = F.interpolate(
            x,
            size=F8.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        G8 = self.gate16_8(F8, x)

        x = torch.cat([x, G8], dim=1)

        x = self.na16_8(x)

        x = self.reduce16_8(x)

        DS8 = x

        # =================================================
        # Stage 8 -> 4
        # =================================================

        x = F.interpolate(
            x,
            size=F4.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        G4 = self.gate8_4(F4, x)

        x = torch.cat([x, G4], dim=1)

        x = self.na8_4(x)

        x = self.reduce8_4(x)

        # =================================================
        # ASPP
        # =================================================

        x = self.aspp(x)

        # =================================================
        # Prediction
        # =================================================

        logits = self.head(x)

        if self.use_deep_supervision:

            ds16 = self.ds16(DS16)

            ds8 = self.ds8(DS8)

            return logits, ds16, ds8

        return logits